name: Vibe Board CI/CD

on:
  push:
    branches: [ "main" ] # main 브랜치에 push될 때 워크플로를 실행합니다.

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name's Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/vibe-board:latest # Docker Hub 사용자 이름과 이미지 태그를 지정합니다.

  deploy:
    needs: build-and-push # build-and-push 작업이 성공해야 실행됩니다.
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Naver Cloud Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.NAVER_CLOUD_HOST }}
          username: ${{ secrets.NAVER_CLOUD_USER }}
          key: ${{ secrets.NAVER_CLOUD_SSH_KEY }}
          script: |
            # Docker Hub에서 최신 이미지를 pull합니다.
            docker pull ${{ secrets.DOCKER_USERNAME }}/vibe-board:latest
            
            # 기존에 실행 중인 컨테이너가 있다면 중지하고 삭제합니다.
            if [ "$(docker ps -q -f name=vibe-app)" ]; then
                docker stop vibe-app
                docker rm vibe-app
            fi
            
            # 호스트에 데이터 디렉토리가 없으면 생성합니다.
            if [ ! -d "/root/vibe/data" ]; then
              mkdir -p /root/vibe/data
            fi

            # 호스트에 posts.json 파일이 없으면, 이미지에서 기본 파일을 복사하여 초기화합니다.
            if [ ! -f "/root/vibe/data/posts.json" ]; then
              echo "posts.json not found on host. Copying default from image."
              docker run --rm --entrypoint cat ${{ secrets.DOCKER_USERNAME }}/vibe-board:latest /app/data/posts.json > /root/vibe/data/posts.json
            fi

            # README.md에 명시된 데이터 보존을 위한 볼륨 마운트를 적용하여 새 컨테이너를 실행합니다.
            # 호스트의 /root/data 디렉토리를 컨테이너의 /app/data와 연결합니다.
            docker run -d -p 3001:3001 \
              -v /root/vibe/data:/app/data \
              --name vibe-app \
              ${{ secrets.DOCKER_USERNAME }}/vibe-board:latest

            # 사용하지 않는 Docker 이미지를 정리하여 서버 용량을 확보합니다.
            docker image prune -af